PrescriptionPushSystem/PrescriptionPushSystem/urls.py
from apscheduler.schedulers.background import BackgroundScheduler
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from uploadTimer.views import upload_prescription_job

sched = BackgroundScheduler()
sched.add_job(upload_prescription_job, 'interval', minutes=1)
sched.start()

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^management/', include(('management.urls', 'management'), namespace='management')),
]

PrescriptionPushSystem/management/urls.py
# coding:utf-8
"""
  Time : 2022/4/3 3:04
  Author : vincent
  FileName: urls
  Software: PyCharm
  Last Modified by: vincent
  Last Modified time: 2022/4/3 3:04
"""
from django.conf.urls import url

from management import views

urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^changeVerifyCode/', views.change_verify_code, name='changeVerifyCode'),
    url(r'^index/', views.index, name='index'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^home/', views.home, name='home'),
    url(r'^userManage/(?P<type>\w+)/', views.user_manage, name='userManage'),
    url(r'^tableData/(?P<type>\w+)/', views.table_data, name='tableData'),
    url(r'^updatePass/', views.update_pass, name='updatePass'),
    url(r'^presUpload/(?P<type>\w+)/', views.pres_upload, name='presUpload'),
    url(r'^presQuery/(?P<type>\w+)/', views.pres_query, name='presQuery'),
    url(r'^company/', views.get_hos_properties, name='company'),
    url(r'^addressManage/(?P<type>\w+)/', views.address_manage, name='addressManage')
]

PrescriptionPushSystem/templates/prescriptionManage/edit_address.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>订单收货信息添加</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    {#  <link rel="stylesheet" href="../../../layuiadmin/layui/css/layui.css" media="all">#}
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="layui-form" lay-filter="orderAddressEdit" id="orderAddressEdit" style="padding: 20px 30px 0 0;">
    <div class="layui-form-item">
        <label class="layui-form-label" style="width: 85px"><span class="red">*</span>地址类型：</label>
        <div class="layui-input-inline">
            <input type="radio" name="is_hos_addr" id="is_hos_addr" value="1" title="医院" lay-filter="isHosAddrCheck">
            <input type="radio" name="is_hos_addr" id="is_hos_addr" value="2" title="个人" lay-filter="isHosAddrCheck">
            <input type="hidden" name="is_hos_addr_passed" id="is_hos_addr_passed" value="{{ addr_info.is_hos_addr }}">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label" style="width: 85px"><span class="red">*</span>收货人姓名：</label>
        <div class="layui-input-inline">
            <input type="text" name="consignee" id="consignee" autocomplete="off" class="layui-input">
            <input type="hidden" name="consignee_passed" id="consignee_passed" value="{{ addr_info.consignee }}" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label" style="width: 85px"><span class="red">*</span>收货人电话：</label>
        <div class="layui-input-inline">
            <input type="text" name="con_tel" id="con_tel" autocomplete="off" class="layui-input">
            <input type="hidden" name="con_tel_passed" id="con_tel_passed" value="{{ addr_info.con_tel }}" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label control_label" style="width: 85px"><span class="red">*</span>收货地址</label>
        <div class="layui-input-block">
            <div class="layui-input-inline" style="width: 150px">
                <select name="comProvince" id="comProvince">
                    <option value="">请选择省</option>
                </select>
                <input type="hidden" name="province_passed" id="province_passed" value="{{ addr_info.province }}" class="layui-input">
            </div>
            <div class="layui-input-inline" style="width: 150px">
                <select name="comCity" id="comCity">
                    <option value="">请选择市</option>
                </select>
                <input type="hidden" name="city_passed" id="city_passed" value="{{ addr_info.city }}" class="layui-input">
            </div>
            <div class="layui-input-inline" style="width: 150px">
                <select name="comZone" id="comZone">
                    <option value="">请选择区(县)</option>
                </select>
                <input type="hidden" name="zone_passed" id="zone_passed" value="{{ addr_info.zone }}" class="layui-input">
            </div>
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label control_label" style="width: 85px"><span class="red">*</span>详细地址</label>
        <div class="layui-input-inline">
            <input type="text" name="addrStr" id="addrStr" lay-verify="required" class="table_input" style="width: 500px">
            <input type="hidden" name="add_passed" id="add_passed" value="{{ addr_info.addr_detail }}" class="layui-input">
        </div>
    </div>
    <input type="hidden" class="table_input" value="{{ addr_id }}" name="addressId" id="addressId">
    <div class="layui-form-item layui-hide">
        <input type="button" lay-submit lay-filter="LAY-user-front-submit" id="LAY-user-back-submit" value="确认">
    </div>
</div>

<script src="{% static 'layui/layui.js' %}"></script>
<script src="{% static 'js/jquery-1.12.3.min.js' %}"></script>
<script src="{% static 'js/region.js' %}"></script>
{#<script type="text/javascript" src="{% static 'js/hospital/jQuery.md5.js' %}"></script>#}
<script>
    window.onload=function () {
        var cp = document.getElementById('comProvince');
        var cc = document.getElementById('comCity');
        var cz = document.getElementById('comZone');
        region(cp,cc,cz);
    };

    var callbackdata = function () {
        var addrDatas = form.val("orderAddressEdit");   //获取表单值
        {#console.log(addrDatas);#}
        console.log(addrDatas);
        if (addrDatas.is_hos_addr == "") {
            layer.msg("请选择地址类型！");
            $("#is_hos_addr").focus();
            return false;
        }
        if (addrDatas.comProvince == "") {
            layer.msg("请选择省！");
            $("#comProvince").focus();
            return false;
        }
        if (addrDatas.comCity == "") {
            layer.msg("请选择市！");
            $("#comCity").focus();
            return false;
        }
        if (addrDatas.comZone == "") {
            layer.msg("请选择区！");
            $("#comZone").focus();
            return false;
        }
        if (addrDatas.consignee == " ") {
            layer.msg("请输入收货人姓名！");
            $("#consignee").focus();
            return false;
        }
        if (addrDatas.con_tel == " ") {
            layer.msg("请输入收货人电话！");
            $("#con_tel").focus();
            return false;
        }
        if (addrDatas.addrStr === " ") {
            layer.msg("请输入详细收货地址！");
            $("#addrStr").focus();
            return false;
        }
        return addrDatas;
    };


    layui.use(['form', 'layer', 'laydate'], function () {
        var $ = layui.jquery;
        window.form = layui.form;
        {#var form = layui.form;#}
        window.layer = layui.layer;
        var laydate = layui.laydate;

        form.val('orderAddressEdit',{
            'is_hos_addr':$("#is_hos_addr_passed").val()
            ,'consignee':$("#consignee_passed").val()
            ,'con_tel':$("#con_tel_passed").val()
            ,'comProvince':$("#province_passed").val()
            ,'comCity':$("#city_passed").val()
            ,'comZone':$("#zone_passed").val()
            ,'addrStr':$("#add_passed").val()
        });
        form.render();
        form.render('select');

        //时间段
        lay('.laydate-item').each(function () {
            laydate.render({
                elem: this
                , trigger: 'click'
                , type: 'datetime'
            });
        });

        form.render('select');

        form.on('radio(isHosAddrCheck)', function (data) {
            if (data.value == '1'){
                $.get("{% url 'management:company' %}",function (data) {
                    {#console.log(data)#}
                    form.val('orderAddressEdit', {
                        "consignee": data.companyname
                        ,"con_tel": data.companytel
                        ,"comProvince": data.companyprovince
                        ,"comCity": data.companycity
                        ,"comZone": data.companyzone
                        ,"addrStr": data.companyaddress
                    });
                    form.render('select');
                });
            }else if (data.value == '2'){
                form.val('orderAddressEdit', {
                        "consignee": ' '
                        ,"con_tel": ' '
                        ,"comProvince": ' '
                        ,"comCity": ' '
                        ,"comZone": ' '
                        ,"addrStr": ' '
                    });
                form.render('select');
            }
        });
    });
</script>
</body>
</html>

PrescriptionPushSystem/templates/prescriptionManage/prescriptionQuery.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>处方查询列表</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <link href="{% static 'fonts/iconfont.css' %}" rel="stylesheet" type="text/css"/>
</head>
<body>
<div class="padding_10">
    <div class="layui-row">
        <div class="layui-card">
            <div class="layui-card-body">
                <div class="form-box">
                    <div class="layui-form layui-form-item">
                        <div class="layui-inline">
                            <div class="layui-form-mid">处方状态:</div>
                            <div class="layui-input-inline" style="width: 160px">
                                <select name="uploadStatus" id="uploadStatus">
                                    <option value="" >全部</option>
                                    <option value="0" >未上传</option>
                                    <option value="-1" >成功</option>
                                    <option value="99" >失败</option>
                                </select>
                            </div>
                            <div class="layui-form-mid">开始时间:</div>
                            <div class="layui-input-inline">
                                <input type="text" class="layui-input test-laydate-item" autocomplete="on" name="startDate" id="startDate">
                            </div>
                            <div class="layui-form-mid">结束时间</div>
                            <div class="layui-input-inline">
                                <input type="text" name="endDate" id="endDate" autocomplete="on" class="layui-input test-laydate-item">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <div class="layui-form-mid">客户姓名:</div>
                            <div class="layui-input-inline" style="width: 120px">
                                <input type="text" name="userName" id="userName" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid">医生姓名:</div>
                            <div class="layui-input-inline" style="width: 120px">
                                <input type="text" name="doctorName" id="doctorName" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid">订单号:</div>
                            <div class="layui-input-inline">
                                <input type="text" name="orderId" id="orderId" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid">处方号:</div>
                            <div class="layui-input-inline">
                                <input type="text" name="PresNum" id="PresNum" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-inline">
                                <button class="layui-btn layuiadmin-btn-admin" lay-submit
                                        lay-filter="LAY-prescription-search">
                                    <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <table id="LAY-prescription-query-manage" lay-filter="LAY-prescription-query-manage"></table>
                {% verbatim %}
                <script id="isSufferTpl" type="text/html">
                    {{ d.is_suffering == 0 ? '非煎煮' : '<span style="color: red;">煎煮</span>'}}
                </script>
                <script id="uploadStatusTpl" type="text/html">
                    {{d.upload_status == -1 ? '<span style="color: green;">上传成功</span>':
                    d.upload_status == 0 ? '<span style="color: lightseagreen;">待上传</span>' :
                    d.upload_status >= 1 ? '<span style="color: red;">上传失败</span>':
                    ''}}
                </script>
                <script id="genderTpl" type="text/html">
                    {{ d.gender == 0 ? '女' : '男'}}
                </script>
                {% endverbatim %}
            </div>
        </div>
    </div>
</div>
<script src="{% static 'layui/layui.js' %}"></script>
<script src="{% static 'js/jquery-1.12.3.min.js' %}"></script>
<script>
    //JavaScript代码区域

    layui.use(['element', 'form', 'table', 'laydate', 'layer'], function () {
        var $ = layui.jquery;
        var element = layui.element;
        var form = layui.form;
        window.table = layui.table;
        var layer = layui.layer;
        var laydate = layui.laydate;

        //时间段
        lay('.test-laydate-item').each(function () {
            laydate.render({
                elem: this
                , trigger: 'click'
                , type: 'datetime'
            });
        });

        //请求用户表信息，渲染
        table.render({
            elem: '#LAY-prescription-query-manage'
            , url: '{% url 'management:tableData' type='midPrescriptionTable' %}'
            , page: true
            {#,height: 'full-100'#}
            , limit: 10
            , limits: [10, 15, 20]
            , cols: [[
                {field: 'pres_num', title: '医院处方号',width:160, align: 'center'}
                , {field: 'order_id', title: '康美订单号',width:140, align: 'center'}
                , {field: 'treat_card', title: '就诊ID',width:100, align: 'center'}
                , {field: 'user_name', title: '患者姓名',width:90, align: 'center'}
                , {field: 'gender', title: '性别', align: 'center',width:60,templet:'#genderTpl'}
                , {field: 'age', title: '年龄',width:60, align: 'center'}
                , {field: 'doctor', title: '开方医生',width:90, align: 'center'}
                , {field: 'consignee', title: '收货人', align: 'center',width:150}
                , {field: 'con_tel', title: '收货人电话', align: 'center',width:130}
                , {field: 'addr_str', title: '收货地址',width:200, align: 'center'}
                , {field: 'pres_time', title: '处方时间',width:160, align: 'center'}
                , {field: 'send_goods_time', title: '送货时间',width:160, align: 'center'}
                , {field: 'is_suffering', title: '是否煎煮',width:90, align: 'center',templet: '#isSufferTpl'}
                , {field: 'upload_status', title: '上传状态',width:90, align: 'center',templet:'#uploadStatusTpl'}
                , {field: 'description', title: '描述信息',width:200, align: 'center'}
            ]]
        });

        //监听搜索
        form.on('submit(LAY-prescription-search)', function (data) {
            var field = data.field;
            console.log(field);
            //执行重载
            table.reload('LAY-prescription-query-manage', {
                where: {
                    uploadStatus:field.uploadStatus,
                    startDate: field.startDate,
                    endDate: field.endDate,
                    userName:field.userName,
                    doctorName: field.doctorName,
                    orderId:field.orderId,
                    presNum:field.PresNum,
                },
                page: {
                    curr: 1
                }
            });
            return false;
        });
    })


</script>
</body>
</html>

PrescriptionPushSystem/templates/prescriptionManage/upload_prescriptions.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>处方上传</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <link href="{% static 'fonts/iconfont.css' %}" rel="stylesheet" type="text/css"/>
</head>
<body>
<div class="padding_10">
    <div class="layui-row">
        <div class="layui-card">
            <div class="layui-card-body">
                <div class="form-box">
                    <div class="layui-form layui-form-item">
                        <div class="layui-inline">
                            <div class="layui-form-mid">客户姓名:</div>
                            <div class="layui-input-inline" style="width: 120px">
                                <input type="text" name="userName" id="userName" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid">处方号:</div>
                            <div class="layui-input-inline">
                                <input type="text" name="presNum" id="presNum" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <div class="layui-form-mid">开始时间:</div>
                            <div class="layui-input-inline">
                                <input type="text" class="layui-input test-laydate-item" autocomplete="" name="startDate" id="startDate">
                            </div>
                            <div class="layui-form-mid">结束时间</div>
                            <div class="layui-input-inline">
                                <input type="text" name="endDate" id="endDate" autocomplete="" class="layui-input test-laydate-item">
                            </div>
                        </div>
                        <div class="layui-inline">
                            <div class="layui-inline">
                                <button class="layui-btn layuiadmin-btn-admin" lay-submit
                                        lay-filter="LAY-order-back-search">
                                    <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                                </button>
                                <input type="hidden" name="prescriptionFlag" value="{{ flag }}" id="prescriptionFlag"/>
                            </div>
                        </div>
                    </div>
                </div>
                <table id="LAY-orderAudit-back-manage" lay-filter="LAY-orderAudit-back-manage"></table>
                {% verbatim %}
                <script type="text/html" id="table-entryAddress">
                    {{#  if(d.is_associate == 1){ }}
                    <span style="color: green;">处方已关联地址</span>
                    {{#  } else { }}
                    <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="entryAddress" style="text-decoration: none">
                        <i class="iconfont icon-tianjia"></i>地址录入</a>
                    {{#  } }}
                </script>
                <script id="isSufferTpl" type="text/html">
                    {{ d.is_suffering == 0 ? '饮片' : d.is_suffering == 1 ? '<span style="color: red;">煎煮</span>' : '未知'}}
                </script>
                <script id="genderTpl" type="text/html">
                    {{ d.gender == 0 ? '女' : '男'}}
                </script>
                {% endverbatim %}
            </div>
        </div>
    </div>
</div>
<script src="{% static 'layui/layui.js' %}"></script>
<script src="{% static 'js/jquery-1.12.3.min.js' %}"></script>
<script>
    //JavaScript代码区域

    layui.use(['element', 'form', 'table', 'laydate', 'layer'], function () {
        var $ = layui.jquery;
        var element = layui.element;
        var form = layui.form;
        window.table = layui.table;
        var layer = layui.layer;
        var laydate = layui.laydate;
        var pres_flag = $("#prescriptionFlag").val();

        //时间段
        lay('.test-laydate-item').each(function () {
            laydate.render({
                elem: this
                , trigger: 'click'
                , type: 'datetime'
            });
        });

        //请求用户表信息，渲染
        table.render({
            elem: '#LAY-orderAudit-back-manage'
            , url: '{% url 'management:tableData' type='view_table' %}' + '?flag=' + pres_flag
            , page: true
            {#,height: 'full-100'#}
            , limit: 10
            , limits: [10, 15, 20]
            , cols: [[
                {field: 'pres_num', title: '处方号',width:160, align: 'center'}
                , {field: 'username', title: '客户姓名',width:90, align: 'center'}
                , {field: 'gender', title: '性别', align: 'center',width:60,templet:'#genderTpl'}
                , {field: 'age', title: '年龄',width:60, align: 'center'}
                , {field: 'treat_card', title: '客户ID',width:100, align: 'center'}
                , {field: 'amount', title: '剂数',width:60, align: 'center'}
                , {field: 'is_suffering', title: '是否煎煮',width:90, align: 'center',templet: '#isSufferTpl'}
                , {field: 'suffering_num', title: '煎煮袋数',width:90, align: 'center'}
                , {field: 'pres_time', title: '处方时间',width:160, align: 'center'}
                , {field: 'hos_depart', title: '科室',width:100,align: 'center'}
                , {field: 'doctor', title: '医生',width:80,align: 'center'}
                , {fixed: 'right', title: '操作', align: 'center',width:180, toolbar: '#table-entryAddress'}
            ]]
        });

        //监听搜索
        form.on('submit(LAY-order-back-search)', function (data) {
            var field = data.field;
            {#console.log(field);#}
            //执行重载
            table.reload('LAY-orderAudit-back-manage', {
                where: {
                    userName:field.userName,
                    presNum:field.presNum,
                    startDate:field.startDate,
                    endDate:field.endDate
                },
                page: {
                    curr: 1
                }
            });
            return false;
        });

        //监听单元格事件
        table.on('tool(LAY-orderAudit-back-manage)', function (obj) {
            var data = obj.data;
            {#console.log(data);#}
            var presNum = data.pres_num;
            var treatCard = data.treat_card;
            if (obj.event === 'entryAddress'){
                var url = '{% url 'management:presUpload' type='entryAddress' %}' + '?flag=' + pres_flag + '&pres_num=' + presNum + '&custom_num=' + treatCard;
                {#console.log(url);#}
                var tab_id = "entry_address";
                var title = "处方地址录入";
                parent.addTabNew(tab_id,url,title);
            }
        });

    })


</script>
</body>
</html>