PrescriptionPushSystem/PrescriptionPushSystem/urls.py
from apscheduler.schedulers.background import BackgroundScheduler
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from uploadTimer.views import upload_prescription_job

sched = BackgroundScheduler()
sched.add_job(upload_prescription_job, 'interval', minutes=1)
sched.start()

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^management/', include(('management.urls', 'management'), namespace='management')),
]

PrescriptionPushSystem/management/urls.py
# coding:utf-8
"""
  Time : 2022/4/3 3:04
  Author : vincent
  FileName: urls
  Software: PyCharm
  Last Modified by: vincent
  Last Modified time: 2022/4/3 3:04
"""
from django.conf.urls import url

from management import views

urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^changeVerifyCode/', views.change_verify_code, name='changeVerifyCode'),
    url(r'^index/', views.index, name='index'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^home/', views.home, name='home'),
    url(r'^userManage/(?P<type>\w+)/', views.user_manage, name='userManage'),
    url(r'^tableData/(?P<type>\w+)/', views.table_data, name='tableData'),
    url(r'^updatePass/', views.update_pass, name='updatePass'),
    url(r'^presUpload/(?P<type>\w+)/', views.pres_upload, name='presUpload'),
    url(r'^presQuery/(?P<type>\w+)/', views.pres_query, name='presQuery'),
    url(r'^company/', views.get_hos_properties, name='company'),
    url(r'^addressManage/(?P<type>\w+)/', views.address_manage, name='addressManage')
]

PrescriptionPushSystem/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
</head>
<body>
<div class="padding_10">
    <div class="head-title clearfix">
        <h1>控制台</h1>
    </div>
</div>
</body>
</html>

PrescriptionPushSystem/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>中药房管理平台</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/backstage/favicon.png' %}"/>
    <link href="{% static 'fonts/iconfont.css' %}" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="{% static '/layui/css/layui.css' %}">
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <div class="layui-logo" onclick="Refresh();">中药房处方推送系统</div>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item">
                <a href="javascript:;">
                    <i class="iconfont icon-guanliyuan"></i>&nbsp;&nbsp;你好！{{ name }}
                </a>
                <input type="hidden" id="login_name" value="{{ name }} ">
                <dl class="layui-nav-child">
                    <dd><a href="javascript:void(0)" onclick="updatepass()"><span
                            class="iconfont icon-icon_password"></span>&nbsp;&nbsp;修改密码</a></dd>
                    <dd><a href="javascript:void(0)" class="" onclick="dropout()"><span
                            class="iconfont icon-084tuichu"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;退出</a></dd>
                </dl>
            </li>
        </ul>
    </div>
    <div class="layui-side layui-bg-black">
        <div class="layui-side-scroll">
            <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
            <ul class="layui-nav layui-nav-tree" lay-shrink="all" lay-filter="management_nav">
                <li class="layui-nav-item">
                    <a href="javascript:;"><span class="iconfont icon-jiaoyiguanli"></span>&nbsp;&nbsp;处方管理</a>
                    <dl class="layui-nav-child">
                        <dd>
                            <a href="javascript:;"><span class="iconfont icon-wj-wjsc"></span>&nbsp;&nbsp;处方上传</a>
                            <ol class="layui-nav-child">
                                <li><a data-url="{% url 'management:presUpload' type='MZ_home' %}" data-id="MZ_pres_upload" data-title="门诊处方" class="nav-active"
                                       href="javascript:;" data-type="tabAdd">&nbsp;&nbsp;&nbsp;<span class="iconfont icon-yishengmenzhen1"></span>&nbsp;&nbsp;门诊处方</a>
                                </li>
                                <li><a data-url="{% url 'management:presUpload' type='ZY_home' %}" data-id="ZY_pres_upload" data-title="住院处方" class="nav-active"
                                       href="javascript:;" data-type="tabAdd">&nbsp;&nbsp;&nbsp;<span class="iconfont icon--_zhuyuan"></span>&nbsp;&nbsp;住院处方</a>
                                </li>
                            </ol>
                        </dd>
                        <dd><a data-url="{% url 'management:presQuery' type='home' %}" data-id="prescri_query" data-title="处方查询" class="nav-active"
                               href="javascript:;" data-type="tabAdd">&nbsp;&nbsp;&nbsp;<span class="iconfont icon-sousuowenjian"></span>&nbsp;&nbsp;处方查询</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item">
                    <a href="javascript:;"><span class="iconfont icon-xitongguanli2"></span>&nbsp;&nbsp;系统管理</a>
                    <dl class="layui-nav-child">
                        <dd><a data-url="{% url 'management:userManage' type='home' %}" data-id="user_manage" data-title="用户管理"
                               class="nav-active" href="javascript:;" data-type="tabAdd">&nbsp;&nbsp;&nbsp;<span class="iconfont icon-guanliyuan1"></span>&nbsp;&nbsp;用户管理</a></dd>
                    </dl>
                </li>
            </ul>
        </div>
    </div>
    <div class="layui-body">
        <!-- 内容主体区域 -->
        <div class="layui-tab" lay-allowClose="true" lay-filter="management_tab">
            <ul class="layui-tab-title">
                <li class="layui-this" lay-id="home">Home</li>
            </ul>
            <div class="layui-tab-content">
                <div class="layui-tab-item layui-show">
                    <iframe src="{% url 'management:home' %}" scrolling="no" frameborder="0"></iframe>
{#                    <iframe src="{% url 'management:home' %}" frameborder="0" class="layui-iframe"></iframe>#}
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'layui/layui.js' %}"></script>
<script src="{% static 'js/jquery-1.12.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jQuery.md5.js' %}"></script>
<script>
    //JavaScript代码区域

    //md5
    function md5_code(data) {
        return $.md5(data)
    }

    //修改密码
    function updatepass() {
        layui.use(['element', 'layer', 'table'], function () {
            var element = layui.element;
            var layer = layui.layer;
            var $ = layui.jquery;
            var table = layui.table;
            layer.open({
                type: 2
                , title: '修改密码'
                , content: '{% url 'management:updatePass' %}'
                , area: ['420px', '250px']
                , btn: ['保存', '取消']
                , btnAlign: 'c'
                , yes: function (index) {
                    var body = layer.getChildFrame('body', index); //得到iframe页的body内容
                    var formdata = {
                        uName: $("#login_name").val(),
                        prePassword: md5_code(body.find("#pre_password").val()),
                        newPassword: md5_code(body.find("#new_password").val()),
                    };
                    {#console.log(formdata);#}
                    $.ajax({
                        url: "{% url 'management:updatePass' %}",
                        data: formdata,
                        dataType: "TEXT",
                        type: "POST",
                        csrfmiddlewaretoken: '{{ csrf_token  }}',
                        success: function (res) {
                            {#console.log(typeof res);#}
                            {#console.log(res);#}
                            var msg = eval("(" + res + ")");        //坑！必须转换成json对象后才能判断status
                            {#console.log(typeof msg);#}
                            {#console.log(msg);#}
                            if (msg.status === 'success') {
                                alert("用户: 【" + formdata['uName'] + "】密码修改成功！")
                            } else {
                                alert("用户: 【" + formdata['uName'] + "】 密码修改失败！\n原因：" + msg.message)
                            }
                            setTimeout(function () {
                                layer.close(index);     //关闭弹层
                            }, 600);
                        }
                    });
                }
            });
        });
    }


    //退出系统
    function dropout() {
        layui.use('layer', function () {
            var layer = layui.layer;
            layer.confirm('是否确定退出系统？', {
                    btn: ['是', '否'],
                    icon: 1,
                },
                function () {
                    location.href = "{% url 'management:logout' %}";
                });
        });
    }

    var lastOperationTime = new Date().getTime();
    var opCurrTime = new Date().getTime();
    var opTimeOut = 1000 * 60 * 15;
    function autoLogout() {
        setInterval(checkLogout, 10000);
        $(document).click(function () {
            lastOperationTime = new Date().getTime();
        });
    }
    function checkLogout() {
        opCurrTime = new Date().getTime();
        if (opCurrTime - lastOperationTime > opTimeOut) {
            alert("操作超时，请重新登录！")
            location.href = "{% url 'management:logout' %}";
        }
    }
    $(function () {
        autoLogout();
    });

    layui.use('element', function () {
        var element = layui.element;
        var $ = layui.jquery;
        //在这里给active绑定几项事件，后面可通过active调用这些事件,
        window.active = {
            tabAdd: function (url, tab_id, tab_title) {
                //新增一个Tab项 传入三个参数，分别对应其标题，tab页面的地址，还有一个规定的tab_id，是标签中data-id的属性值
                element.tabAdd('management_tab', {
                    title: tab_title,
                    content: '<iframe data-frameid="' + tab_id + '" scrolling="auto" frameborder="0" src="' + url + '" style="width:100%;min-height: 660px;"></iframe>',
                    id: tab_id
                })
                element.render('tab');
            },
            tabChange: function (tab_id) {
                //根据传入的id传入到指定的tab项
                element.tabChange('management_tab', tab_id);
            },
            tabDelete: function (tab_id) {
                element.tabDelete("management_tab", tab_id);
            },
            tabDeleteAll: function (tab_ids) {
                $.each(tab_ids, function (i, item) {
                    element.tabDelete("management_tab", item);
                })
            },
        };

        //监听选项卡切换
        element.on('tab(management_tab)', function (data) {
            {#console.log(this); //当前Tab标题所在的原始DOM元素#}
            {#console.log(data.index); //得到当前Tab的所在下标#}
            {#console.log(data.elem); //得到当前的Tab大容器#}
        });

        //当点击有nav-active属性的标签时，即左侧菜单栏中内容 ，触发点击事件
        $('.nav-active').on('click', function (data) {
            var dataid = $(this);
            {#console.log(dataid.attr("data-url"));#}
            if ($(".layui-tab-title li[lay-id=" + dataid.attr("data-id") + "]").length > 0) {
                active.tabChange(dataid.attr("data-id"));
            } else {
                active.tabAdd(dataid.attr("data-url"), dataid.attr("data-id"), dataid.attr("data-title"));
            }
            active.tabChange(dataid.attr("data-id"));  //切换到新增的tab上
        });
    })

    function addTabNew(tab_id, url, title, closed_tab_id) {
        if (closed_tab_id){
            active.tabDelete(closed_tab_id);
        }
        if ($(".layui-tab-title li[lay-id=" + tab_id + "]").length > 0) {
            active.tabDelete(tab_id);
            active.tabAdd(url, tab_id, title);
            active.tabChange(tab_id);  //切换到新增的tab上
        } else {
            active.tabAdd(url, tab_id, title);
            active.tabChange(tab_id);  //切换到
        }
    };



</script>

</body>
</html>

PrescriptionPushSystem/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>中药房处方推送系统</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
<div style="width:100%;height:645px;position: absolute;top:50%;left:50%;margin-top:-320px;margin-left:-50%;">
    <div class="header"></div>
    <div class="center">
        <div class="login_right">
            <div style="width:100%;height:auto;margin-top:150px;">
                <form action="{% url 'management:login' %}" method="post" name="loginForm" id="loginForm" onsubmit="return check();">
                    {% csrf_token %}
                    <div class="login_title">
                        用户登录
                    </div>
                    <div class="login_info">
                        <label>用户名：</label><input type="text" name="username" id="username" class="login_input"
                                                  value=""/>
                        &nbsp;&nbsp;<span id="nameerr" class="errInfo">{% if uperror %}{{ uperror }}
                        {% endif %}</span>
                    </div>
                    <div class="login_info">
                        <label>密　码：</label><input type="password" name="password" id="password" class="login_input"
                                                  value=""/>
                        &nbsp;<span id="pwderr" class="errInfo"></span>
                    </div>
                    <div class="login_info">
                        <label>验证码：</label><input type="text" name="code" id="code" class="login_code"/>&nbsp;&nbsp;
                        <img id="codeImg" width="70px" height="25px" alt="点击更换" title="点击更换" src=""/>
                        &nbsp;<span id="codeerr" class="errInfo">{% if cerror %}{{ cerror }}
                        {% endif %}</span>
                    </div>
                    <div class="login_info">
                        <input type="submit" name="loginBtn" id="loginButton" value="登录" class="btn"/>
                        <input type="reset" name="cancelBtn" id="cancleButton" value="取消" class="btn"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="bottom">
        Copyright &copy; 2022 中药房处方推送系统
    </div>
</div>
<script src="{% static 'js/jquery-1.12.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jQuery.md5.js' %}"></script>
<script type="text/javascript">
    var errInfo = "";
    $(document).ready(function () {
        changeCode();
        $("#codeImg").bind("click", changeCode);
        if (errInfo != "") {
            if (errInfo.indexOf("验证码") > -1) {
                $("#codeerr").show();
                $("#codeerr").html(errInfo);
                $("#code").focus();
            } else {
                $("#nameerr").show();
                $("#nameerr").html(errInfo);
            }
        }
        $("#username").focus();
    })

    function genTimestamp() {
        var time = new Date();
        return time.getTime();
    }

    function changeCode() {
        $("#codeImg").attr("src", "{% url 'management:changeVerifyCode' %}?t=" + genTimestamp());
    }

    function resetErr() {
        $("#nameerr").hide();
        $("#nameerr").html("");
        $("#pwderr").hide();
        $("#pwderr").html("");
        $("#codeerr").hide();
        $("#codeerr").html("");
    }

    function check() {
        resetErr();
        if ($("#username").val() == "") {
            $("#nameerr").show();
            $("#nameerr").html("用户名不能为空！");
            $("#username").focus();
            return false;
        }
        if ($("#password").val() == "") {
            $("#pwderr").show();
            $("#pwderr").html("密码不能为空！");
            $("#password").focus();
            return false;
        }
        if ($("#code").val() == "") {
            $("#codeerr").show();
            $("#codeerr").html("验证码不能为空！");
            $("#code").focus();
            return false;
        }
        $("#password").val($.md5($("#password").val()).toLowerCase());
        sessionStorage.clear();
        return true;
    }

</script>
</body>
</html>